In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] # value at specific index position

8

In [5]:
arr[1:5] # index slicing. Not including last position

array([1, 2, 3, 4])

In [6]:
arr[:6] # everything upto 6. Like arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:] # everything beyond 5 including value at index 5 

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# numpy array is different from python list. Because their ability to broadcast 

In [9]:
# if we select any slice of array, any changes in this slice array will affect the original array

In [10]:
slice_of_array = arr[0:6]

In [11]:
slice_of_array[0:3] = 100

In [12]:
arr # when we modify the slice_of_array the original array is also modified. To avoid this copy the array to another array and modify the new array

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [13]:
new_slice_array = arr.copy()
new_slice_array[0:4] = 25
print(new_slice_array)
print(arr)

[25 25 25 25  4  5  6  7  8  9 10]
[100 100 100   3   4   5   6   7   8   9  10]


In [14]:
# 2 d Array indexing

In [15]:
arra_2d = np.array([[4,5,6],[8,6,4],[4,7,3]])
arra_2d

array([[4, 5, 6],
       [8, 6, 4],
       [4, 7, 3]])

In [16]:
arra_2d[2][1] # selecting element at 3 row and 2 column. Indexing started at 0

7

In [17]:
arra_2d[2,1] # another notation

7

In [18]:
 arra_2d[:2,1:] # selecting rows upto 2 and columns from 1

array([[5, 6],
       [6, 4]])

In [19]:
# conditional selection

In [20]:
arra = np.arange(1,11)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
bool_arra = arra>5

In [22]:
arra[bool_arra]

array([ 6,  7,  8,  9, 10])

In [23]:
# we can do it in simple
arra[arra>5]

array([ 6,  7,  8,  9, 10])

In [24]:
arra_2d_n = np.arange(0,50).reshape(5,10)
arra_2d_n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
bool_n = arra_2d_n <= 14

In [43]:
bool_n

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])