In [48]:
# Numpy Numerical Python

In [ ]:
# Numpy Arrays

In [4]:
array = [1,2,3] # Simple list Array

In [5]:
import numpy as np

In [6]:
num_array = np.array(array)

In [7]:
print(array)
num_array
# difference between normal array and numpy array
# Check the output

[1, 2, 3]


array([1, 2, 3])

In [8]:
my_list_of_list = [[1,2,3],[8,6,7],[6,7,8]]
my_list_of_list

[[1, 2, 3], [8, 6, 7], [6, 7, 8]]

In [9]:
np.array(my_list_of_list)

array([[1, 2, 3],
       [8, 6, 7],
       [6, 7, 8]])

In [10]:
# np.arange(start, stop, stepsize, dtype)
# shift + tab for documentation
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)
# 1 dimensional zero array with specific column

array([0., 0., 0.])

In [12]:
np.zeros((4,3))
# Two dimensional array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(3)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [15]:
np.eye(4)
# Eigen matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5) # One dimension
np.random.rand(5,5) # Two dimension

array([[0.3989005 , 0.47825038, 0.49284625, 0.64173737, 0.93631604],
       [0.64475353, 0.67684214, 0.18560786, 0.49175646, 0.25369102],
       [0.74159406, 0.47742516, 0.03100676, 0.1548578 , 0.34266675],
       [0.3037298 , 0.0867547 , 0.40650482, 0.65111193, 0.18111642],
       [0.02438616, 0.87068973, 0.68157502, 0.69827897, 0.78224804]])

In [17]:
# Normal Distribution or Gaussian Distribution
np.random.randn(4,4)

array([[-2.06923388, -1.20382581, -1.51930019, -0.11129587],
       [-0.24946368, -1.006762  , -1.18417654,  0.43086739],
       [-1.00899216, -1.22500045, -1.38836008,  0.01580973],
       [-1.07565232,  1.44786106,  0.05316816,  0.27455602]])

In [18]:
# Random integer between a specific range
np.random.randint(1,100)

51

In [28]:
# select 10 random integer
arr_m = np.random.randint(1,100,10)

In [29]:
array_re = np.arange(25)
array_re

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
array_sha = array_re.reshape(5,5)

In [31]:
 arr_m.max() # maximum value in the array

89

In [32]:
arr_m.min() # minimum value in array

21

In [33]:
arr_m.argmax() # index position of the value

9

In [34]:
arr_m.argmin()

3

In [38]:
array_sha.shape # shape of the array

(5, 5)

In [40]:
array_sha.dtype # type of values in the array

dtype('int64')

In [43]:
array_mul = ['s',1,2,3,4,5]
array_multi = np.array(array_mul)

In [44]:
array_multi.dtype

dtype('<U1')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

9