In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8] # value at specific index position

8

In [7]:
arr[1:5] # index slicing. Not including last position

array([1, 2, 3, 4])

In [8]:
arr[:6] # everything upto 6. Like arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:] # everything beyond 5 including value at index 5 

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# numpy array is different from python list. Because their ability to broadcast 

In [11]:
# if we select any slice of array, any changes in this slice array will affect the original array

In [12]:
slice_of_array = arr[0:6]

In [13]:
slice_of_array[0:3] = 100

In [15]:
arr # when we modify the slice_of_array the original array is also modified. To avoid this copy the array to another array and modify the new array

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [16]:
new_slice_array = arr.copy()
new_slice_array[0:4] = 25
print(new_slice_array)
print(arr)

[25 25 25 25  4  5  6  7  8  9 10]
[100 100 100   3   4   5   6   7   8   9  10]
