In [1]:
# Array with Array
# Array with scalars
# Universal functions

In [2]:
import numpy as np

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr
# Not concatinating. It adds the elements with same index number

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
# also for subtraction, devision , multiplication
print(arr - arr)
print(arr * arr)
print(arr/arr) # in this case zero division error occurs and 0/0 will give a nan (not a number)
print(arr-100)
print(1/arr) # 1/0 infinity. check the output
arr ** 2

[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


/Users/rencheerajmohan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
/Users/rencheerajmohan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])